import { AlertTriangle, ArrowLeft } from "lucide-react";
import { Link } from "wouter";
import { SiteShell } from "@/components/site-shell";

const copy: Record<string, { title: string; intro: string; sections: [string, string][] }> = {
  "/datenschutz": { title: "Datenschutz", intro: "Wir behandeln deine Angaben mit Sorgfalt. Diese Platzhalterseite wird vor dem öffentlichen Betrieb durch eine Schweizer Fachstelle geprüft.", sections: [["Verantwortliche Stelle", "AUTO DOKTOR · Thun, Schweiz. Die vollständigen Angaben werden nach der rechtlichen Prüfung ergänzt."], ["Welche Daten wir bearbeiten", "Für eine Fallaufnahme können Fahrzeug-, Kontakt- und freiwillig übermittelte Mediendaten verarbeitet werden. Wir verwenden sie nur, um deinen Fall zu beurteilen und die gewünschte Kontaktaufnahme zu ermöglichen."], ["Rechtlicher Hinweis", "Diese Darstellung ist noch nicht vollständig und stellt keine Rechtsberatung dar."]]},
  "/impressum": { title: "Impressum", intro: "Die Angaben für das vollständige Schweizer Impressum werden vor dem Launch ergänzt und fachlich geprüft.", sections: [["Anbieter", "AUTO DOKTOR · Thun, Schweiz"], ["Kontakt", "Die definitive Geschäftsadresse und vertretungsberechtigte Person folgen nach der Gründung."], ["Rechtlicher Hinweis", "Platzhalter — Schweizer Rechtsprüfung ausstehend."]]},
  "/agb": { title: "Allgemeine Geschäftsbedingungen", intro: "Unsere AGB werden passend zu den tatsächlichen Leistungen von AUTO DOKTOR formuliert. Bis dahin gilt: Diese Seite ist nur ein Platzhalter.", sections: [["Leistungsumfang", "Die digitale Vorprüfung ist eine erste Orientierung und ersetzt keine technische Diagnose."], ["Termine und Anfragen", "Eine Terminanfrage ist erst nach Bestätigung durch AUTO DOKTOR verbindlich."], ["Rechtlicher Hinweis", "Schweizer Rechtsprüfung ausstehend."]]},
  "/ai-disclaimer": { title: "Hinweis zur digitalen Vorprüfung", intro: "Technologie kann beim Sortieren helfen. Sie entscheidet nicht, ob du weiterfahren darfst.", sections: [["Was die Vorprüfung leistet", "Deine Angaben werden strukturiert, damit mögliche Ursachen und sinnvolle nächste Schritte verständlich dargestellt werden können."], ["Was sie nicht leistet", "Die Ausgabe ist keine definitive Diagnose, keine Sicherheitsfreigabe und kein Ersatz für eine Untersuchung durch eine qualifizierte Fachperson."], ["Bei Gefahr", "Bei Rauch, Brandgeruch, Flüssigkeitsaustritt, ungewöhnlichen Geräuschen oder unsicherem Fahrverhalten: anhalten, absichern und professionelle Hilfe beiziehen."]]},
};

export default function Legal({ path }: { path: string }) {
  const page = copy[path] ?? copy["/datenschutz"];
  return <SiteShell><section className="mx-auto max-w-[850px] px-5 py-16 lg:px-8 lg:py-24"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#438a88]" data-testid="link-legal-back"><ArrowLeft size={16} /> Zur Startseite</Link><div className="mt-12 rounded-[26px] border border-[#e1b6a4] bg-[#fff1e9] p-7 sm:p-10"><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-[#f6a15a] text-[#23384a]"><AlertTriangle size={21} /></span><div><p className="font-mono-ui text-[10px] font-medium uppercase tracking-[.18em] text-[#a05a3d]">Schweizer Rechtsprüfung ausstehend</p><p className="mt-2 text-sm leading-6 text-[#854334]">Diese Inhalte sind Platzhalter und dürfen vor der rechtlichen Freigabe nicht als vollständige Rechtsinformation verstanden werden.</p></div></div></div><h1 className="mt-12 font-display text-5xl font-bold leading-[.95] tracking-[-.065em] text-[#23384a] sm:text-7xl" data-testid={`text-legal-title-${path.slice(1)}`}>{page.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#5c717a]">{page.intro}</p><div className="mt-14 space-y-0 border-t border-[#cbdadc]">{page.sections.map(([title, text], index) => <section key={title} className="grid gap-3 border-b border-[#cbdadc] py-7 sm:grid-cols-[.4fr_1fr]"><p className="font-mono-ui text-[10px] uppercase tracking-[.14em] text-[#438a88]">0{index + 1}</p><div><h2 className="font-display text-xl font-bold tracking-[-.03em]">{title}</h2><p className="mt-3 text-sm leading-7 text-[#63777d]">{text}</p></div></section>)}</div></section></SiteShell>;
}