import { useState, type ChangeEvent, type FormEvent } from "react";
import { ArrowLeft, ArrowRight, Check, CircleHelp, FileVideo, LoaderCircle, LockKeyhole, ShieldCheck, Trash2, Upload, X } from "lucide-react";
import { useLocation } from "wouter";
import { CaseInputDrivingStatus, ContactInputPreferredContact, MediaInputKind, useCreateCase } from "@workspace/api-client-react";
import type { CaseInput, MediaInput, VehicleInput } from "@workspace/api-client-react";
import { SiteShell } from "@/components/site-shell";
import { useI18n } from "@/lib/i18n";

type LocalMedia = MediaInput & { url: string };
type FormState = { vehicle: VehicleInput; category: string; symptoms: string; faultCodes: string; media: LocalMedia[]; drivingStatus: CaseInputDrivingStatus; firstName: string; lastName: string; phone: string; email: string; preferredContact: ContactInputPreferredContact; consentAccepted: boolean };

const initialState: FormState = {
  vehicle: { make: "", model: "", year: new Date().getFullYear(), engine: "", mileage: 0, fuel: "", transmission: "", registration: "", vin: "" },
  category: "", symptoms: "", faultCodes: "", media: [], drivingStatus: CaseInputDrivingStatus.unsure,
  firstName: "", lastName: "", phone: "", email: "", preferredContact: ContactInputPreferredContact.phone, consentAccepted: false,
};

function Input({ label, value, onChange, placeholder, type = "text", required = false, testId }: { label: string; value: string | number; onChange: (value: string) => void; placeholder?: string; type?: string; required?: boolean; testId: string }) {
  return <label className="grid gap-2 text-sm font-bold text-[#334e5d]">{label}{required && <span className="ml-1 text-[#c5694c]">*</span>}<input className="h-12 w-full rounded-xl border border-[#cbdadc] bg-[#f8faf9] px-4 text-sm font-semibold text-[#23384a] outline-none transition-colors placeholder:font-normal placeholder:text-[#9aabad] focus:border-[#438a88] focus:ring-4 focus:ring-[#438a88]/10" type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} data-testid={testId} /></label>;
}

function TextArea({ label, value, onChange, placeholder, testId }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; testId: string }) {
  return <label className="grid gap-2 text-sm font-bold text-[#334e5d]">{label}<textarea className="min-h-36 resize-y rounded-xl border border-[#cbdadc] bg-[#f8faf9] p-4 text-sm font-semibold text-[#23384a] outline-none transition-colors placeholder:font-normal placeholder:text-[#9aabad] focus:border-[#438a88] focus:ring-4 focus:ring-[#438a88]/10" value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} data-testid={testId} /></label>;
}

export default function ProblemReport() {
  const { t } = useI18n();
  const [, setLocation] = useLocation();
  const steps = [t("wizard.steps.vehicle"), t("wizard.steps.problem"), t("wizard.steps.symptoms"), t("wizard.steps.codes"), t("wizard.steps.media"), t("wizard.steps.driving"), t("wizard.steps.contact"), t("wizard.steps.submit")];
  const categories = ["category.engine", "category.transmission", "category.brakes", "category.chassis", "category.electrics", "category.battery", "category.climate", "category.emissions", "category.noise", "category.start", "category.warning", "category.other"].map(t);
  const [step, setStep] = useState(0);
  const [form, setForm] = useState<FormState>(initialState);
  const [error, setError] = useState("");
  const createCase = useCreateCase();
  const progress = Math.round(((step + 1) / steps.length) * 100);
  const updateVehicle = (key: keyof VehicleInput, value: string) => setForm((current) => ({ ...current, vehicle: { ...current.vehicle, [key]: key === "year" || key === "mileage" ? Number(value) : value } }));

  const validateStep = () => {
    if (step === 0 && (!form.vehicle.make || !form.vehicle.model || !form.vehicle.year || !form.vehicle.registration)) return t("wizard.validationVehicle");
    if (step === 1 && !form.category) return t("wizard.validationCategory");
    if (step === 2 && form.symptoms.trim().length < 10) return t("wizard.validationSymptoms");
    if (step === 6 && (!form.firstName || !form.lastName || form.phone.length < 5 || !form.email.includes("@"))) return t("wizard.validationContact");
    if (step === 6 && !form.consentAccepted) return t("wizard.validationConsent");
    return "";
  };
  const next = () => { const message = validateStep(); if (message) { setError(message); return; } setError(""); setStep((current) => Math.min(current + 1, steps.length - 1)); };
  const back = () => { setError(""); setStep((current) => Math.max(current - 1, 0)); };
  const handleFile = (event: ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(event.target.files ?? []);
    const accepted = files.map((file) => {
      const kind: MediaInputKind | null = file.type.startsWith("image/") ? MediaInputKind.photo : file.type.startsWith("video/") ? MediaInputKind.video : null;
      const max = kind === MediaInputKind.video ? 30 * 1024 * 1024 : 8 * 1024 * 1024;
      if (!kind || file.size > max) return null;
      return { name: file.name, contentType: file.type, size: file.size, kind, url: URL.createObjectURL(file) };
    }).filter((item): item is LocalMedia => Boolean(item));
    if (accepted.length !== files.length) setError(t("wizard.fileSkipped"));
    setForm((current) => ({ ...current, media: [...current.media, ...accepted].slice(0, 5) }));
    event.target.value = "";
  };
  const removeMedia = (name: string) => setForm((current) => ({ ...current, media: current.media.filter((item) => item.name !== name) }));
  const submit = (event: FormEvent) => {
    event.preventDefault();
    const message = validateStep(); if (message) { setError(message); return; }
    const payload: CaseInput = {
      vehicle: form.vehicle,
      category: form.category,
      symptoms: form.symptoms,
      faultCodes: form.faultCodes.split(",").map((code) => code.trim()).filter(Boolean),
      media: form.media.map(({ url: _url, ...media }) => media),
      drivingStatus: form.drivingStatus,
      contact: { firstName: form.firstName, lastName: form.lastName, phone: form.phone, email: form.email, preferredContact: form.preferredContact },
      consentAccepted: true,
    };
     createCase.mutate({ data: payload }, { onSuccess: (result) => setLocation(`/fall/${result.id}`), onError: () => setError(t("wizard.saveError")) });
  };
  const set = (key: keyof FormState, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));

  return (
    <SiteShell>
      <div className="border-b border-[#d3dfe1] bg-[#d6e8e7]">
         <div className="mx-auto max-w-[1240px] px-5 py-8 lg:px-8 lg:py-10"><div className="flex items-center justify-between gap-4"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.18em] text-[#438a88]">{t("wizard.eyebrow")}</p><h1 className="mt-2 font-display text-3xl font-bold tracking-[-.05em] sm:text-4xl">{t("wizard.title")}</h1></div><span className="hidden rounded-full bg-[#eaf4f2] px-3 py-2 font-mono-ui text-[10px] font-medium text-[#438a88] sm:block" data-testid="status-wizard-progress">{progress}% {t("wizard.done")}</span></div><div className="mt-8 h-1.5 overflow-hidden rounded-full bg-[#b9d1d1]"><div className="h-full rounded-full bg-[#438a88] transition-[width] duration-500" style={{ width: `${progress}%` }} data-testid="progress-wizard" /></div><div className="mt-4 flex justify-between gap-2 overflow-x-auto">{steps.map((label, index) => <span key={label} className={`shrink-0 font-mono-ui text-[9px] uppercase tracking-[.1em] ${index === step ? "font-bold text-[#23384a]" : index < step ? "text-[#438a88]" : "text-[#8fa5a9]"}`} data-testid={`text-step-${index + 1}`}>{String(index + 1).padStart(2, "0")} {label}</span>)}</div></div>
      </div>
      <div className="mx-auto grid max-w-[1240px] gap-10 px-5 py-10 lg:grid-cols-[minmax(0,720px)_280px] lg:px-8 lg:py-16">
        <form onSubmit={submit} className="animate-fade">
          <div className="rounded-[24px] border border-[#cbdadc] bg-[#f5f8f7] p-6 sm:p-10">
            {step === 0 && <div><StepTitle eyebrow="01 · Fahrzeug" title="Welches Auto braucht gerade Aufmerksamkeit?" description="Die Basisdaten helfen uns, deine Situation richtig einzuordnen." /><div className="grid gap-5 sm:grid-cols-2"><Input label="Marke" value={form.vehicle.make} onChange={(v) => updateVehicle("make", v)} placeholder="z. B. Škoda" required testId="input-vehicle-make" /><Input label="Modell" value={form.vehicle.model} onChange={(v) => updateVehicle("model", v)} placeholder="z. B. Octavia" required testId="input-vehicle-model" /><Input label="Jahrgang" type="number" value={form.vehicle.year} onChange={(v) => updateVehicle("year", v)} placeholder="2020" required testId="input-vehicle-year" /><Input label="Kontrollschild" value={form.vehicle.registration} onChange={(v) => updateVehicle("registration", v)} placeholder="BE 123 456" required testId="input-vehicle-registration" /><Input label="Motorisierung" value={form.vehicle.engine} onChange={(v) => updateVehicle("engine", v)} placeholder="z. B. 1.5 TSI" testId="input-vehicle-engine" /><Input label="Kilometerstand" type="number" value={form.vehicle.mileage || ""} onChange={(v) => updateVehicle("mileage", v)} placeholder="z. B. 84200" testId="input-vehicle-mileage" /><SelectField label="Treibstoff" value={form.vehicle.fuel} onChange={(v) => updateVehicle("fuel", v)} options={["Benzin", "Diesel", "Hybrid", "Elektro", "Andere"]} testId="select-vehicle-fuel" /><SelectField label="Getriebe" value={form.vehicle.transmission} onChange={(v) => updateVehicle("transmission", v)} options={["Automatik", "Manuell", "Unbekannt"]} testId="select-vehicle-transmission" /><div className="sm:col-span-2"><Input label="VIN (optional)" value={form.vehicle.vin ?? ""} onChange={(v) => updateVehicle("vin", v)} placeholder="Fahrzeug-Identifikationsnummer" testId="input-vehicle-vin" /></div></div></div>}
            {step === 1 && <div><StepTitle eyebrow="02 · Problem" title="Was ist passiert?" description="Wähle die Kategorie, die sich am ehesten richtig anfühlt. Du musst die Ursache nicht kennen." /><div className="grid gap-3 sm:grid-cols-2">{categories.map((category) => <button type="button" key={category} onClick={() => set("category", category)} className={`flex items-center justify-between rounded-2xl border p-4 text-left text-sm font-bold transition-all ${form.category === category ? "border-[#438a88] bg-[#d6e8e7] text-[#23384a] ring-4 ring-[#438a88]/10" : "border-[#cbdadc] bg-[#f8faf9] text-[#536b74] hover:border-[#438a88]"}`} data-testid={`button-category-${category.toLowerCase().replaceAll(" ", "-")}`}>{category}<span className={`grid h-6 w-6 place-items-center rounded-full border ${form.category === category ? "border-[#438a88] bg-[#438a88] text-[#edf3f2]" : "border-[#cbdadc]"}`}>{form.category === category && <Check size={14} />}</span></button>)}</div></div>}
            {step === 2 && <div><StepTitle eyebrow="03 · Symptome" title="Was bemerkst du genau?" description="Je konkreter deine Beschreibung, desto besser können wir den nächsten Schritt vorbereiten." /><TextArea label="Deine Beschreibung" value={form.symptoms} onChange={(v) => set("symptoms", v)} placeholder="Seit wann tritt es auf? Was hast du gehört, gesehen oder gespürt? Was war unmittelbar davor?" testId="textarea-symptoms" /><div className="mt-5 rounded-2xl bg-[#eaf4f2] p-4 text-xs leading-5 text-[#5c717a]"><CircleHelp size={16} className="mb-2 text-[#438a88]" />Auch Unsicherheiten sind wichtige Informationen. Schreib einfach, was dir aufgefallen ist.</div></div>}
            {step === 3 && <div><StepTitle eyebrow="04 · Fehlercodes" title="Zeigt dein Auto einen Fehlercode?" description="Wenn du einen Code oder eine Warnmeldung kennst, kannst du ihn hier eintragen. Dieser Schritt ist optional." /><TextArea label="Fehlercodes oder Warnmeldungen" value={form.faultCodes} onChange={(v) => set("faultCodes", v)} placeholder="z. B. P0420, Motor kontrollieren, mehrere Codes mit Komma trennen" testId="textarea-fault-codes" /><div className="mt-5 flex gap-3 rounded-2xl border border-[#cbdadc] p-4"><CircleHelp className="shrink-0 text-[#438a88]" size={18} /><p className="text-xs leading-5 text-[#63777d]">Kein Code zur Hand? Kein Problem. Wir können auch mit deiner Beschreibung starten.</p></div></div>}
            {step === 4 && <div><StepTitle eyebrow="05 · Bilder & Videos" title="Kannst du uns etwas zeigen?" description="Ein Foto der Warnleuchte oder ein kurzes Video vom Geräusch kann viel erklären. Dieser Schritt ist optional." /><label className="group flex min-h-48 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-[#a9c8c7] bg-[#eaf4f2] text-center transition-colors hover:border-[#438a88]"><Upload size={26} className="text-[#438a88]" /><span className="mt-4 text-sm font-extrabold text-[#334e5d]">Dateien auswählen</span><span className="mt-1 text-xs text-[#63777d]">JPG, PNG, HEIC bis 8 MB · MP4, MOV bis 30 MB</span><input type="file" multiple accept="image/*,video/*" onChange={handleFile} className="sr-only" data-testid="input-media-upload" /></label><div className="mt-5 grid gap-3">{form.media.map((media) => <div key={media.name} className="flex items-center gap-3 rounded-xl border border-[#cbdadc] bg-[#f8faf9] p-3" data-testid={`preview-media-${media.name}`}><div className="h-14 w-14 overflow-hidden rounded-lg bg-[#d6e8e7]">{media.kind === "photo" ? <img src={media.url} alt={media.name} className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center text-[#438a88]"><FileVideo size={22} /></div>}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{media.name}</p><p className="font-mono-ui text-[10px] text-[#7c9095]">{(media.size / 1024 / 1024).toFixed(1)} MB · {media.kind === "photo" ? "Foto" : "Video"}</p></div><button type="button" onClick={() => removeMedia(media.name)} className="grid h-8 w-8 place-items-center rounded-full text-[#8ba0a4] hover:bg-[#fff0eb] hover:text-[#a05a3d]" data-testid={`button-remove-media-${media.name}`}><Trash2 size={16} /></button></div>)}</div></div>}
            {step === 5 && <div><StepTitle eyebrow="06 · Fahrstatus" title="Kannst du noch sicher weiterfahren?" description="Deine Einschätzung genügt. Bei Unsicherheit wählen wir lieber den vorsichtigen Weg." /><div className="grid gap-3">{([{ value: CaseInputDrivingStatus.yes, title: "Ja, das Auto fährt normal", text: "Keine akute Einschränkung bemerkt." }, { value: CaseInputDrivingStatus.unsure, title: "Ich bin unsicher", text: "Etwas fühlt sich anders an, ich kann es nicht beurteilen." }, { value: CaseInputDrivingStatus.no, title: "Nein, besser nicht", text: "Das Auto steht oder wirkt nicht sicher." }] as const).map((option) => <button type="button" key={option.value} onClick={() => set("drivingStatus", option.value)} className={`flex items-start gap-4 rounded-2xl border p-5 text-left transition-all ${form.drivingStatus === option.value ? "border-[#438a88] bg-[#d6e8e7] ring-4 ring-[#438a88]/10" : "border-[#cbdadc] bg-[#f8faf9] hover:border-[#438a88]"}`} data-testid={`button-driving-${option.value}`}><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full border-2 ${form.drivingStatus === option.value ? "border-[#438a88] bg-[#438a88]" : "border-[#b5c8ca]"}`}>{form.drivingStatus === option.value && <span className="h-2 w-2 rounded-full bg-[#edf3f2]" />}</span><span><span className="block text-sm font-extrabold">{option.title}</span><span className="mt-1 block text-xs text-[#63777d]">{option.text}</span></span></button>)}</div><div className="mt-5 rounded-2xl bg-[#fff0eb] p-4 text-xs leading-5 text-[#854334]"><ShieldCheck size={16} className="mb-2 text-[#a05a3d]" />Bei Rauch, Brandgeruch, Flüssigkeitsaustritt oder unsicherem Fahrverhalten: bitte anhalten und professionelle Hilfe organisieren.</div></div>}
            {step === 6 && <div><StepTitle eyebrow="07 · Kontakt & Zustimmung" title="Wohin dürfen wir unsere Einschätzung schicken?" description="Wir verwenden deine Angaben nur für diesen Fall und melden uns persönlich." /><div className="grid gap-5 sm:grid-cols-2"><Input label="Vorname" value={form.firstName} onChange={(v) => set("firstName", v)} placeholder="z. B. Anna" required testId="input-contact-first-name" /><Input label="Nachname" value={form.lastName} onChange={(v) => set("lastName", v)} placeholder="z. B. Müller" required testId="input-contact-last-name" /><Input label="Telefon" value={form.phone} onChange={(v) => set("phone", v)} placeholder="+41 79 123 45 67" required testId="input-contact-phone" /><Input label="E-Mail" type="email" value={form.email} onChange={(v) => set("email", v)} placeholder="anna@beispiel.ch" required testId="input-contact-email" /></div><fieldset className="mt-6"><legend className="text-sm font-bold text-[#334e5d]">Bevorzugter Kontaktweg</legend><div className="mt-3 flex flex-wrap gap-3">{([{ value: ContactInputPreferredContact.phone, label: "Telefon" }, { value: ContactInputPreferredContact.whatsapp, label: "WhatsApp" }, { value: ContactInputPreferredContact.email, label: "E-Mail" }] as const).map((option) => <button type="button" key={option.value} onClick={() => set("preferredContact", option.value)} className={`rounded-full border px-4 py-2.5 text-xs font-bold transition-colors ${form.preferredContact === option.value ? "border-[#438a88] bg-[#d6e8e7] text-[#23384a]" : "border-[#cbdadc] bg-[#f8faf9] text-[#63777d]"}`} data-testid={`button-preferred-contact-${option.value}`}>{option.label}</button>)}</div></fieldset><div className="mt-8 border-t border-[#d6e2e3] pt-6"><p className="font-mono-ui text-[10px] uppercase tracking-[.14em] text-[#438a88]">Fast fertig</p><div className="mt-4 flex items-center justify-between rounded-xl bg-[#eaf4f2] px-4 py-3 text-sm"><span className="font-bold text-[#63777d]">Deine Fallaufnahme</span><span className="font-extrabold text-[#23384a]">{form.vehicle.make || "Fahrzeug"} · {form.category || "Problem"}</span></div><label className="mt-4 flex cursor-pointer items-start gap-3 rounded-2xl border border-[#cbdadc] bg-[#f8faf9] p-4"><input type="checkbox" checked={form.consentAccepted} onChange={(event) => set("consentAccepted", event.target.checked)} className="mt-0.5 h-5 w-5 accent-[#438a88]" data-testid="input-consent" /><span className="text-xs leading-5 text-[#63777d]">Ich bin einverstanden, dass AUTO DOKTOR meine Angaben zur Bearbeitung dieser Fallaufnahme und zur Kontaktaufnahme verwendet. <span className="font-bold text-[#23384a]">Die digitale Vorprüfung ersetzt keine technische Diagnose.</span></span></label></div></div>}
            {step === 7 && <div><StepTitle eyebrow="08 · Abschicken" title="Bereit für den nächsten Schritt?" description="Prüfe kurz die Zusammenfassung. Danach erstellen wir deinen Fall und bereiten eine erste Einschätzung vor." /><div className="grid gap-3">{[{ label: "Fahrzeug", value: `${form.vehicle.make} ${form.vehicle.model} (${form.vehicle.year})` }, { label: "Problem", value: form.category }, { label: "Fahrstatus", value: form.drivingStatus === "yes" ? "Fährt normal" : form.drivingStatus === "no" ? "Fährt nicht sicher" : "Unsicher" }, { label: "Anhänge", value: `${form.media.length} Datei${form.media.length === 1 ? "" : "en"}` }].map((item) => <div key={item.label} className="flex items-center justify-between gap-4 rounded-xl bg-[#eaf4f2] px-4 py-3" data-testid={`summary-${item.label.toLowerCase()}`}><span className="font-mono-ui text-[10px] uppercase tracking-[.12em] text-[#438a88]">{item.label}</span><span className="text-right text-sm font-extrabold text-[#23384a]">{item.value}</span></div>)}</div><label className="mt-7 flex cursor-pointer items-start gap-3 rounded-2xl border border-[#cbdadc] bg-[#f8faf9] p-4"><input type="checkbox" checked={form.consentAccepted} onChange={(event) => set("consentAccepted", event.target.checked)} className="mt-0.5 h-5 w-5 accent-[#438a88]" data-testid="input-consent" /><span className="text-xs leading-5 text-[#63777d]">Ich bin einverstanden, dass AUTO DOKTOR meine Angaben zur Bearbeitung dieser Fallaufnahme und zur Kontaktaufnahme verwendet. <span className="font-bold text-[#23384a]">Die digitale Vorprüfung ersetzt keine technische Diagnose.</span></span></label></div>}
            {error && <div className="mt-6 flex items-start gap-2 rounded-xl border border-[#e1b6a4] bg-[#fff0eb] p-4 text-sm font-semibold leading-5 text-[#854334]" role="alert" data-testid="error-wizard"><X size={18} className="mt-0.5 shrink-0" />{error}</div>}
            <div className="mt-9 flex items-center justify-between gap-3 border-t border-[#d6e2e3] pt-6"><button type="button" onClick={back} disabled={step === 0 || createCase.isPending} className="inline-flex items-center gap-2 rounded-full px-3 py-3 text-sm font-bold text-[#63777d] transition-colors hover:bg-[#eaf4f2] disabled:invisible" data-testid="button-wizard-back"><ArrowLeft size={17} /> Zurück</button>{step < steps.length - 1 ? <button type="button" onClick={next} className="inline-flex items-center gap-3 rounded-full bg-[#23384a] px-5 py-3.5 text-sm font-extrabold text-[#edf3f2] shadow-[0_4px_0_#132532] transition-transform hover:-translate-y-0.5" data-testid="button-wizard-next">Weiter <ArrowRight size={17} /></button> : <button type="submit" disabled={createCase.isPending} className="inline-flex items-center gap-3 rounded-full bg-[#f6a15a] px-5 py-3.5 text-sm font-extrabold text-[#23384a] shadow-[0_4px_0_#d97b38] transition-transform hover:-translate-y-0.5 disabled:cursor-wait disabled:opacity-70" data-testid="button-submit-case">{createCase.isPending ? <><LoaderCircle size={17} className="animate-spin" /> Wird gespeichert</> : <>Fall absenden <ArrowRight size={17} /></>}</button>}</div>
          </div>
        </form>
        <aside className="hidden lg:block"><div className="sticky top-6 rounded-[22px] bg-[#23384a] p-6 text-[#edf3f2]"><LockKeyhole size={20} className="text-[#f6a15a]" /><h2 className="mt-8 font-display text-2xl font-bold tracking-[-.04em]">In Ruhe ausfüllen.</h2><p className="mt-3 text-sm leading-6 text-[#b9cbd0]">Du kannst jederzeit zurückgehen. Pflichtfelder sind mit einem Stern markiert.</p><div className="mt-8 space-y-4 border-t border-[#3d5969] pt-5">{["Keine Ferndiagnose als Wahrheit", "Fotos bleiben zunächst nur Metadaten", "Persönliche Antwort innert 1 Werktag"].map((text) => <div key={text} className="flex gap-2 text-xs font-semibold"><Check size={15} className="shrink-0 text-[#62c7a1]" />{text}</div>)}</div></div></aside>
      </div>
    </SiteShell>
  );
}

function StepTitle({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <div className="mb-9"><p className="font-mono-ui text-[10px] uppercase tracking-[.18em] text-[#438a88]">{eyebrow}</p><h2 className="mt-3 max-w-xl font-display text-3xl font-bold leading-[1] tracking-[-.055em] sm:text-4xl">{title}</h2><p className="mt-4 max-w-xl text-sm leading-6 text-[#63777d]">{description}</p></div>;
}

function SelectField({ label, value, onChange, options, testId }: { label: string; value: string; onChange: (value: string) => void; options: string[]; testId: string }) {
  return <label className="grid gap-2 text-sm font-bold text-[#334e5d]">{label}<select className="h-12 w-full rounded-xl border border-[#cbdadc] bg-[#f8faf9] px-4 text-sm font-semibold text-[#23384a] outline-none focus:border-[#438a88] focus:ring-4 focus:ring-[#438a88]/10" value={value} onChange={(event) => onChange(event.target.value)} data-testid={testId}><option value="">Bitte wählen</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>;
}